const data = {
    unitTypes: {
        Length: {
            Meter: { 
                Kilometre: ['/', 1000],
                Centimeter: ['x', 100],
                Millimetre: ['x', 1000],
                Mile: ['/', 1609],
                Yard: ['x', 1.094],
                Foot: ['x', 3.281],
                Inch: ['x', 39.37]
            },
            Kilometre: {
                Meter: ['x', 1000],
                Centimeter: ['x', 100000],
                Millimetre: ['x', 1000000],
                Mile: ['/', 1.609],
                Yard: ['x', 1094],
                Foot: ['x', 3281],
                Inch: ['x', 39370]
            },
            Centimeter: {
                Meter: ['/', 100],
                Kilometre: ['/', 100000],
                Millimetre: ['x', 10],
                Mile: ['/', 160900],
                Yard: ['/', 91.44],
                Foot: ['/', 30.48],
                Inch: ['/', 2.54]
            },
            Millimetre: {
                Meter: ['/', 1000],
                Kilometre: ['/', 1000000],
                Centimeter: ['/', 10],
                Mile: ['/', 1609000],
                Yard: ['/', 914.4],
                Foot: ['/', 304.8],
                Inch: ['/', 25.4]
            },
            Mile: {
                Meter: ['x', 1609],
                Kilometre: ['x', 1.609],
                Centimeter: ['x', 160900],
                Millimetre: ['x', 1609000],
                Yard: ['x', 1760],
                Foot: ['x', 5280],
                Inch: ['x', 63360]
            },
            Yard: {
                Meter: ['/', 1.094],
                Kilometre: ['/', 1094],
                Centimeter: ['x', 91.44],
                Millimetre: ['x', 914.4],
                Mile: ['/', 1760],
                Foot: ['x', 3],
                Inch: ['x', 36]
            },
            Foot: {
                Meter: ['/', 3.281],
                Kilometre: ['/', 3281],
                Centimeter: ['x', 30.48],
                Millimetre: ['x', 304.8],
                Mile: ['/', 5280],
                Yard: ['/', 3],
                Inch: ['x', 12]
            },
            Inch: {
                Meter: ['/', 39.37],
                Kilometre: ['/', 39370],
                Centimeter: ['x', 2.54],
                Millimetre: ['x', 25.4],
                Mile: ['/', 63360],
                Yard: ['/', 36],
                Foot: ['/', 12]
            }
        },
        Mass: {
            Gram: {
                Kilogram: ['/', 1000],
                Milligram: ['x', 1000],
                Ounce: ['/', 28.35],
                Pound: ['/', 453.6],
                USTon: ['/', 907200]
            },
            Kilogram: {
                Gram: ['x', 1000],
                Milligram: ['x', 31540000000],
                Ounce: ['x', 35.274],
                Pound: ['x', 2.205],
                USTon: ['/', 907.2]
            },
            Milligram: {
                Gram: ['/', 1000],
                Kilogram: ['/', 1000000],
                Ounce: ['/', 28350],
                Pound: ['/', 453600],
                USTon: ['/', 907200000]
            },
            Ounce: {
                Gram: ['x', 28.35],
                Kilogram: ['/', 35.274],
                Milligram: ['x', 28350],
                Pound: ['/', 16],
                USTon: ['/', 32000]
            },
            Pound: {
                Gram: ['x', 453.6],
                Kilogram: ['/', 2.205],
                Milligram: ['x', 453600],
                Ounce: ['x', 16],
                USTon: ['/', 2000]
            },
            USTon: {
                Gram: ['x', 907200],
                Kilogram: ['x', 907.2],
                Milligram: ['x', 907200000],
                Ounce: ['x', 32000],
                Pound: ['x', 2000]
            }
        },
        Volume: {
            USLiquidGallon: {
                USLiquidQuart: ['x', 4],
                USLiquidPint: ['x', 8],
                USLegalCup: ['x', 15.773],
                USTablespoon: ['x', 256],
                USTeaspoon: ['x', 768],
                FluidOunce: ['x', 128],
                Milliliter: ['x', 3785],
                Liter: ['x', 3.785],
                ImperialFluidOunce: ['x', 133.2],
                ImperialGallon: ['/', 1.201],
                ImperialQuart: ['x', 3.331],
                ImperialPint: ['x', 6.661],
                ImperialCup: ['x', 13.323],
                ImperialTablespoon: ['x', 213.2],
                ImperialTeaspoon: ['x', 639.5],
                CubicInch: ['x', 231],
                CubicFoot: ['/', 7.48],
                CubicMeter: ['/', 264.2]
            },
            USLiquidQuart: {
                USLiquidGallon: ['/', 4],
                USLiquidPint: ['x', 2],
                USLegalCup: ['x', 3.943],
                USTablespoon: ['x', 64],
                USTeaspoon: ['x', 192],
                FluidOunce: ['x', 32],
                Milliliter: ['x', 946.4],
                Liter: ['x', 1.057],
                ImperialFluidOunce: ['x', 33.307],
                ImperialGallon: ['/', 4.804],
                ImperialQuart: ['/', 1.201],
                ImperialPint: ['x', 1.665],
                ImperialCup: ['x', 3.331],
                ImperialTablespoon: ['x', 53.291],
                ImperialTeaspoon: ['x', 159.9],
                CubicInch: ['x', 57.75],
                CubicFoot: ['/', 29.922],
                CubicMeter: ['/', 1057]
            },
            USLiquidPint: {
                USLiquidGallon: ['/', 8],
                USLiquidQuart: ['/', 2],
                USLegalCup: ['x', 1.972],
                USTablespoon: ['x', 32],
                USTeaspoon: ['x', 96],
                FluidOunce: ['x', 16],
                Milliliter: ['x', 473.2],
                Liter: ['/', 2.113],
                ImperialFluidOunce: ['x', 16.653],
                ImperialGallon: ['/', 9.608],
                ImperialQuart: ['/', 2.402],
                ImperialPint: ['/', 1.201],
                ImperialCup: ['x', 1.665],
                ImperialTablespoon: ['x', 26.646],
                ImperialTeaspoon: ['x', 79.937],
                CubicInch: ['x', 28.875],
                CubicFoot: ['/', 59.844],
                CubicMeter: ['/', 2113]
            },
            USLegalCup: {
                USLiquidGallon: ['/', 15.772],
                USLiquidQuart: ['/', 3.943],
                USLiquidPint: ['/', 1.972],
                USTablespoon: ['x', 16.231],
                USTeaspoon: ['x', 48.692],
                FluidOunce: ['x', 8.115],
                Milliliter: ['x', 240],
                Liter: ['/', 4.167],
                ImperialFluidOunce: ['x', 8.447],
                ImperialGallon: ['/', 18.942],
                ImperialQuart: ['/', 4.736],
                ImperialPint: ['/', 2.368],
                ImperialCup: ['/', 1.184],
                ImperialTablespoon: ['x', 13.515],
                ImperialTeaspoon: ['x', 40.545],
                CubicInch: ['x', 14.646],
                CubicFoot: ['/', 118],
                CubicMeter: ['/', 4167]
            },
            USTablespoon: {
                USLiquidGallon: ['/', 256],
                USLiquidQuart: ['/', 64],
                USLiquidPint: ['/', 32],
                USLegalCup: ['/', 16.231],
                USTeaspoon: ['x', 3],
                FluidOunce: ['/', 2],
                Milliliter: ['x', 14.787],
                Liter: ['/', 67.628],
                ImperialFluidOunce: ['/', 1.922],
                ImperialGallon: ['/', 307.4],
                ImperialQuart: ['/', 76.861],
                ImperialPint: ['/', 38.43],
                ImperialCup: ['/', 19.215],
                ImperialTablespoon: ['/', 1.201],
                ImperialTeaspoon: ['x', 2.498],
                CubicInch: ['/', 1.108],
                CubicFoot: ['/', 1915],
                CubicMeter: ['/', 67630]
            },
            USTeaspoon: {
                USLiquidGallon: ['/', 768],
                USLiquidQuart: ['/', 192],
                USLiquidPint: ['/', 96],
                USLegalCup: ['/', 48.692],
                USTablespoon: ['/', 3],
                FluidOunce: ['/', 6],
                Milliliter: ['x', ],
                Liter: ['/', 202.9],
                ImperialFluidOunce: ['/', 5.765],
                ImperialGallon: ['/', 922.3],
                ImperialQuart: ['/', 230.6],
                ImperialPint: ['/', 115.3],
                ImperialCup: ['/', 57.646],
                ImperialTablespoon: ['/', 3.603],
                ImperialTeaspoon: ['/', 1.201],
                CubicInch: ['/', 3.325],
                CubicFoot: ['/', 5745],
                CubicMeter: ['/', 202900]
            },
            FluidOunce: {
                USLiquidGallon: ['/', 128],
                USLiquidQuart: ['/', 32],
                USLiquidPint: ['/', 16],
                USLegalCup: ['/', 8.115],
                USTablespoon: ['x', 2],
                USTeaspoon: ['x', 6],
                Milliliter: ['x', 29.574],
                Liter: ['/', 33.814],
                ImperialFluidOunce: ['x', 1.041],
                ImperialGallon: ['/', 153.7],
                ImperialQuart: ['/', 38.43],
                ImperialPint: ['/', 19.215],
                ImperialCup: ['/', 9.608],
                ImperialTablespoon: ['x', 1.665],
                ImperialTeaspoon: ['x', 4.996],
                CubicInch: ['x', 1.805],
                CubicFoot: ['/', 957.5],
                CubicMeter: ['/', 33810]
            },
            Milliliter: {
                USLiquidGallon: ['/', 3785],
                USLiquidQuart: ['/', 946.4],
                USLiquidPint: ['/', 473.2],
                USLegalCup: ['/', 240],
                USTablespoon: ['/', 14.787],
                USTeaspoon: ['/', 4.929],
                FluidOunce: ['/', 29.574],
                Liter: ['/', 1000],
                ImperialFluidOunce: ['/', 28.413],
                ImperialGallon: ['/', 4546],
                ImperialQuart: ['/', 1137],
                ImperialPint: ['/', 568.3],
                ImperialCup: ['/', 284.1],
                ImperialTablespoon: ['/', 17.758],
                ImperialTeaspoon: ['/', 5.919],
                CubicInch: ['/', 16.387],
                CubicFoot: ['/', 28320],
                CubicMeter: ['/', 1000000]
            },
            Liter: {
                USLiquidGallon: ['/', 3.785],
                USLiquidQuart: ['x', 1.057],
                USLiquidPint: ['x', 2.113],
                USLegalCup: ['x', 4.167],
                USTablespoon: ['x', 67.628],
                USTeaspoon: ['x', 202.9],
                FluidOunce: ['x', 33.814],
                Milliliter: ['x', 1000],
                ImperialFluidOunce: ['x', 35.195],
                ImperialGallon: ['/', 4.546],
                ImperialQuart: ['/', 1.136],
                ImperialPint: ['x', 1.76],
                ImperialCup: ['x', 3.52],
                ImperialTablespoon: ['x', 56.312],
                ImperialTeaspoon: ['x', 168.9],
                CubicInch: ['x', 61.024],
                CubicFoot: ['/', 28.317],
                CubicMeter: ['/', 1000]
            },
            ImperialFluidOunce: {
                USLiquidGallon: ['/', 133.2],
                USLiquidQuart: ['/', 33.307],
                USLiquidPint: ['/', 16.654],
                USLegalCup: ['/', 8.447],
                USTablespoon: ['x', 1.922],
                USTeaspoon: ['x', 5.765],
                FluidOunce: ['/', 1.041],
                Milliliter: ['x', 28.413],
                Liter: ['/', 35.195],
                ImperialGallon: ['/', 160],
                ImperialQuart: ['/', 40],
                ImperialPint: ['/', 20],
                ImperialCup: ['/', 10],
                ImperialTablespoon: ['x', 1.6],
                ImperialTeaspoon: ['x', 4.8],
                CubicInch: ['x', 1.734],
                CubicFoot: ['/', 996.6],
                CubicMeter: ['/', 35200]
            },
            ImperialGallon: {
                USLiquidGallon: ['x', 1.201],
                USLiquidQuart: ['x', 4.804],
                USLiquidPint: ['x', 9.608],
                USLegalCup: ['x', 18.942],
                USTablespoon: ['x', 307.4],
                USTeaspoon: ['x', 922.3],
                FluidOunce: ['x', 153.7],
                Milliliter: ['x', 4546],
                Liter: ['x', 4.546],
                ImperialFluidOunce: ['x', 160],
                ImperialQuart: ['x', 4],
                ImperialPint: ['x', 8],
                ImperialCup: ['x', 16],
                ImperialTablespoon: ['x', 256],
                ImperialTeaspoon: ['x', 768],
                CubicInch: ['x', 277.4],
                CubicFoot: ['/', 6.229],
                CubicMeter: ['/', 220]
            },
            ImperialQuart: {
                USLiquidGallon: ['/', 3.331],
                USLiquidQuart: ['x', 1.201],
                USLiquidPint: ['x', 2.402],
                USLegalCup: ['x', 4.736],
                USTablespoon: ['x', 76.861],
                USTeaspoon: ['x', 230.6],
                FluidOunce: ['x', 38.43],
                Milliliter: ['x', 1137],
                Liter: ['x', 1.137],
                ImperialFluidOunce: ['x', 40],
                ImperialGallon: ['/', 4],
                ImperialPint: ['x', 2],
                ImperialCup: ['x', 4],
                ImperialTablespoon: ['x', 64],
                ImperialTeaspoon: ['x', 192],
                CubicInch: ['x', 69.355],
                CubicFoot: ['/', 24.915],
                CubicMeter: ['/', 879.9]
            },
            ImperialPint: {
                USLiquidGallon: ['/', 6.661],
                USLiquidQuart: ['/', 1.665],
                USLiquidPint: ['x', 1.201],
                USLegalCup: ['x', 2.368],
                USTablespoon: ['x', 38.43],
                USTeaspoon: ['x', 115.3],
                FluidOunce: ['x', 19.215],
                Milliliter: ['x', 568.3],
                Liter: ['/', 1.76],
                ImperialFluidOunce: ['x', 20],
                ImperialGallon: ['/', 8],
                ImperialQuart: ['/', 2],
                ImperialCup: ['x', 2],
                ImperialTablespoon: ['x', 32],
                ImperialTeaspoon: ['x', 96],
                CubicInch: ['x', 34.677],
                CubicFoot: ['/', 49.831],
                CubicMeter: ['/', 1760]
            },
            ImperialCup: {
                USLiquidGallon: ['/', 13.323],
                USLiquidQuart: ['/', 3.331],
                USLiquidPint: ['/', 1.665],
                USLegalCup: ['x', 1.184],
                USTablespoon: ['x', 19.215],
                USTeaspoon: ['x', 57.646],
                FluidOunce: ['x', 9.608],
                Milliliter: ['x', 284.1],
                Liter: ['/', 3.52],
                ImperialFluidOunce: ['x', 10],
                ImperialGallon: ['/', 16],
                ImperialQuart: ['/', 4],
                ImperialPint: ['/', 2],
                ImperialTablespoon: ['x', 16],
                ImperialTeaspoon: ['x', 48],
                CubicInch: ['x', 17.339],
                CubicFoot: ['/', 99.661],
                CubicMeter: ['/', 3520]
            },
            ImperialTablespoon: {
                USLiquidGallon: ['/', 213.2],
                USLiquidQuart: ['/', 53.291],
                USLiquidPint: ['/', 26.646],
                USLegalCup: ['/', 13.515],
                USTablespoon: ['x', 1.201],
                USTeaspoon: ['x', 3.603],
                FluidOunce: ['/', 1.665],
                Milliliter: ['x', 17.758],
                Liter: ['/', 56.312],
                ImperialFluidOunce: ['/', 1.6],
                ImperialGallon: ['/', 256],
                ImperialQuart: ['/', 64],
                ImperialPint: ['/', 32],
                ImperialCup: ['/', 3],
                ImperialTeaspoon: ['x', 3],
                CubicInch: ['x', 1.084],
                CubicFoot: ['/', 1595],
                CubicMeter: ['/', 56310]
            },
            ImperialTeaspoon: {
                USLiquidGallon: ['/', 639.5],
                USLiquidQuart: ['/', 159.9],
                USLiquidPint: ['/', 79.937],
                USLegalCup: ['/', 40.545],
                USTablespoon: ['/', 2.498],
                USTeaspoon: ['x', 1.201],
                FluidOunce: ['/', 4.996],
                Milliliter: ['x', 5.919],
                Liter: ['/', 168.9],
                ImperialFluidOunce: ['/', 4.8],
                ImperialGallon: ['/', 768],
                ImperialQuart: ['/', 192],
                ImperialPint: ['/', 96],
                ImperialCup: ['/', 48],
                ImperialTablespoon: ['/', 3],
                CubicInch: ['/', 2.768],
                CubicFoot: ['/', 4784],
                CubicMeter: ['/', 168900]
            },
            CubicInch: {
                USLiquidGallon: ['/', 231],
                USLiquidQuart: ['/', 57.75],
                USLiquidPint: ['/', 28.875],
                USLegalCup: ['/', 14.646],
                USTablespoon: ['x', 1.108],
                USTeaspoon: ['x', 3.325],
                FluidOunce: ['/', 1.805],
                Milliliter: ['x', 16.387],
                Liter: ['/', 61.024],
                ImperialFluidOunce: ['/', 1.734],
                ImperialGallon: ['/', 277.4],
                ImperialQuart: ['/', 69.355],
                ImperialPint: ['/', 34.677],
                ImperialCup: ['/', 17.339],
                ImperialTablespoon: ['/', 1.084],
                ImperialTeaspoon: ['x', 2.768],
                CubicFoot: ['/', 1728],
                CubicMeter: ['/', 61020]
            },
            CubicFoot: {
                USLiquidGallon: ['x', 7.481],
                USLiquidQuart: ['x', 29.922],
                USLiquidPint: ['x', 59.844],
                USLegalCup: ['x', 118],
                USTablespoon: ['x', 1915],
                USTeaspoon: ['x', 5745],
                FluidOunce: ['x', 957.5],
                Milliliter: ['x', 28320],
                Liter: ['x', 28.317],
                ImperialFluidOunce: ['x', 996.6],
                ImperialGallon: ['x', 6.229],
                ImperialQuart: ['x', 24.915],
                ImperialPint: ['x', 49.831],
                ImperialCup: ['x', 99.661],
                ImperialTablespoon: ['x', 1595],
                ImperialTeaspoon: ['x', 4784],
                CubicInch: ['x', 1728],
                CubicMeter: ['/', 35.315]
            },
            CubicMeter: {
                USLiquidGallon: ['x', 264.2],
                USLiquidQuart: ['x', 1057],
                USLiquidPint: ['x', 2113],
                USLegalCup: ['x', 4167],
                USTablespoon: ['x', 67630],
                USTeaspoon: ['x', 202900],
                FluidOunce: ['x', 33810],
                Milliliter: ['x', 1000000],
                Liter: ['x', 1000],
                ImperialFluidOunce: ['x', 35200],
                ImperialGallon: ['x', 220],
                ImperialQuart: ['x', 879.9],
                ImperialPint: ['x', 1760],
                ImperialCup: ['x', 3520],
                ImperialTablespoon: ['x', 56310],
                ImperialTeaspoon: ['x', 168900],
                CubicInch: ['x', 61020],
                CubicFoot: ['x', 35.315],
            }
        },
        Time: {
            Millisecond: { // only "exact convert", all others are from google convert'
                Second: ['/', 1000], 
                Minute: ['/', 60000], 
                Hour: ['/', 3600000],
                Day: ['/', 86400000],
                Week: ['/', 604800000],
                Month: ['/', 2628001150],
                Year: ['/', 31536086400] 
            },
            Second: {
                Millisecond: ['x', 1000],
                Minute: ['/', 60],
                Hour: ['/', 3600],
                Day: ['/', 86400],
                Week: ['/', 604800],
                Month: ['/', 2628000],
                Year: ['/', 31540000]
            },
            Minute: {
                Millisecond: ['x', 60000],
                Second: ['x', 60],
                Hour: ['/', 60],
                Day: ['/', 1440],
                Week: ['/', 10080],
                Month: ['/', 43800],
                Year: ['/', 525600]
            },
            Hour: {
                Millisecond: ['x', 3600000],
                Second: ['x', 3600],
                Minute: ['x', 60],
                Day: ['/', 24],
                Week: ['/', 168],
                Month: ['/', 730],
                Year: ['/', 8760]
            },
            Day: {
                Millisecond: ['x', 86400000],
                Second: ['x', 86400],
                Minute: ['x', 1440],
                Hour: ['x', 24],
                Week: ['/', 7],
                Month: ['/', 30.417],
                Year: ['/', 365]
            },
            Week: {
                Millisecond: ['x', 604800000],
                Second: ['x', 604800],
                Minute: ['x', 10080],
                Hour: ['x', 168],
                Day: ['x', 7],
                Month: ['/', 4.345],
                Year: ['/', 52.143]
            },
            Month: {
                Millisecond: ['x', 2628000000],
                Second: ['x', 2628000],
                Minute: ['x', 43800],
                Hour: ['x', 730],
                Day: ['x', 30.417],
                Week: ['x', 4.345],
                Year: ['/', 12]
            },
            Year: {
                Millisecond: ['x', 31540000000],
                Second: ['x', 31540000],
                Minute: ['x', 525600],
                Hour: ['x', 8760],
                Day: ['x', 365],
                Week: ['x', 52.143],
                Month: ['x', 12]
            }
        },
        Temp: {
            Celsius: {

            },
            Kelvin: {

            },
            Fahrenheit: {

            }
        }
    }
}

// const data = {
  
// }

export default data;