const data = {
    unitTypes: {
        Length: {
            Meter: { 
                Kilometre: ['/', 1000],
                Centimeter: ['x', 100],
                Millimetre: ['x', 1000],
                Mile: ['/', 1609],
                Yard: ['x', 1.094],
                Foot: ['x', 3.281],
                Inch: ['x', 39.37]
            },
            Kilometre: {
                Meter: ['x', 1000],
                Centimeter: ['x', 100000],
                Millimetre: ['x', 1000000],
                Mile: ['/', 1.609],
                Yard: ['x', 1094],
                Foot: ['x', 3281],
                Inch: ['x', 39370]
            },
            Centimeter: {
                Meter: ['/', 100],
                Kilometre: ['/', 100000],
                Millimetre: ['x', 10],
                Mile: ['/', 160900],
                Yard: ['/', 91.44],
                Foot: ['/', 30.48],
                Inch: ['/', 2.54]
            },
            Millimetre: {
                Meter: ['/', 1000],
                Kilometre: ['/', 1000000],
                Centimeter: ['/', 10],
                Mile: ['/', 1609000],
                Yard: ['/', 914.4],
                Foot: ['/', 304.8],
                Inch: ['/', 25.4]
            },
            Mile: {
                Meter: ['x', 1609],
                Kilometre: ['x', 1.609],
                Centimeter: ['x', 160900],
                Millimetre: ['x', 1609000],
                Yard: ['x', 1760],
                Foot: ['x', 5280],
                Inch: ['x', 63360]
            },
            Yard: {
                Meter: ['/', 1.094],
                Kilometre: ['/', 1094],
                Centimeter: ['x', 91.44],
                Millimetre: ['x', 914.4],
                Mile: ['/', 1760],
                Foot: ['x', 3],
                Inch: ['x', 36]
            },
            Foot: {
                Meter: ['/', 3.281],
                Kilometre: ['/', 3281],
                Centimeter: ['x', 30.48],
                Millimetre: ['x', 304.8],
                Mile: ['/', 5280],
                Yard: ['/', 3],
                Inch: ['x', 12]
            },
            Inch: {
                Meter: ['/', 39.37],
                Kilometre: ['/', 39370],
                Centimeter: ['x', 2.54],
                Millimetre: ['x', 25.4],
                Mile: ['/', 63360],
                Yard: ['/', 36],
                Foot: ['/', 12]
            }
        },
        Mass: {
            Gram: {
                Kilogram: ['/', 1000],
                Milligram: ['x', 1000],
                Ounce: ['/', 28.35],
                Pound: ['/', 453.6],
                USTon: ['/', 907200]
            },
            Kilogram: {
                Gram: ['x', 1000],
                Milligram: ['x', 31540000000],
                Ounce: ['x', 35.274],
                Pound: ['x', 2.205],
                USTon: ['/', 907.2]
            },
            Milligram: {
                Gram: ['/', 1000],
                Kilogram: ['/', 1000000],
                Ounce: ['/', 28350],
                Pound: ['/', 453600],
                USTon: ['/', 907200000]
            },
            Ounce: {
                Gram: ['x', 28.35],
                Kilogram: ['/', 35.274],
                Milligram: ['x', 28350],
                Pound: ['/', 16],
                USTon: ['/', 32000]
            },
            Pound: {
                Gram: ['x', 453.6],
                Kilogram: ['/', 2.205],
                Milligram: ['x', 453600],
                Ounce: ['x', 16],
                USTon: ['/', 2000]
            },
            USTon: {
                Gram: ['x', 907200],
                Kilogram: ['x', 907.2],
                Milligram: ['x', 907200000],
                Ounce: ['x', 32000],
                Pound: ['x', 2000]
            }
        },
        Volume: {
            USLiquidGallon: {
                USLiquidQuart: [],
                USLiquidPint: [],
                USLegalCup: [],
                USTablespoon: [],
                USTeaspoon: [],
                FluidOunce: [],
                Milliliter: [],
                Liter: [],
                ImperialFluidOunce: [],
                ImperialGallon: [],
                ImperialQuart: [],
                ImperialPint: [],
                ImperialCup: [],
                ImperialTablespoon: [],
                ImperialTeaspoon: [],
                CubicInch: [],
                CubicFoot: [],
                CubicMeter: []
            },
            USLiquidQuart: {
                USLiquidGallon: [],
                USLiquidPint: [],
                USLegalCup: [],
                USTablespoon: [],
                USTeaspoon: [],
                FluidOunce: [],
                Milliliter: [],
                Liter: [],
                ImperialFluidOunce: [],
                ImperialGallon: [],
                ImperialQuart: [],
                ImperialPint: [],
                ImperialCup: [],
                ImperialTablespoon: [],
                ImperialTeaspoon: [],
                CubicInch: [],
                CubicFoot: [],
                CubicMeter: []
            },
            USLiquidPint: {
                USLiquidGallon: [],
                USLiquidQuart: [],
                USLegalCup: [],
                USTablespoon: [],
                USTeaspoon: [],
                FluidOunce: [],
                Milliliter: [],
                Liter: [],
                ImperialFluidOunce: [],
                ImperialGallon: [],
                ImperialQuart: [],
                ImperialPint: [],
                ImperialCup: [],
                ImperialTablespoon: [],
                ImperialTeaspoon: [],
                CubicInch: [],
                CubicFoot: [],
                CubicMeter: []
            },
            USLegalCup: {
                USLiquidGallon: [],
                USLiquidQuart: [],
                USLiquidPint: [],
                USTablespoon: [],
                USTeaspoon: [],
                FluidOunce: [],
                Milliliter: [],
                Liter: [],
                ImperialFluidOunce: [],
                ImperialGallon: [],
                ImperialQuart: [],
                ImperialPint: [],
                ImperialCup: [],
                ImperialTablespoon: [],
                ImperialTeaspoon: [],
                CubicInch: [],
                CubicFoot: [],
                CubicMeter: []
            },
            USTablespoon: {
                USLiquidGallon: [],
                USLiquidQuart: [],
                USLiquidPint: [],
                USLegalCup: [],
                USTeaspoon: [],
                FluidOunce: [],
                Milliliter: [],
                Liter: [],
                ImperialFluidOunce: [],
                ImperialGallon: [],
                ImperialQuart: [],
                ImperialPint: [],
                ImperialCup: [],
                ImperialTablespoon: [],
                ImperialTeaspoon: [],
                CubicInch: [],
                CubicFoot: [],
                CubicMeter: []
            },
            USTeaspoon: {
                USLiquidGallon: [],
                USLiquidQuart: [],
                USLiquidPint: [],
                USLegalCup: [],
                USTablespoon: [],
                FluidOunce: [],
                Milliliter: [],
                Liter: [],
                ImperialFluidOunce: [],
                ImperialGallon: [],
                ImperialQuart: [],
                ImperialPint: [],
                ImperialCup: [],
                ImperialTablespoon: [],
                ImperialTeaspoon: [],
                CubicInch: [],
                CubicFoot: [],
                CubicMeter: []
            },
            FluidOunce: {
                USLiquidGallon: [],
                USLiquidQuart: [],
                USLiquidPint: [],
                USLegalCup: [],
                USTablespoon: [],
                USTeaspoon: [],
                Milliliter: [],
                Liter: [],
                ImperialFluidOunce: [],
                ImperialGallon: [],
                ImperialQuart: [],
                ImperialPint: [],
                ImperialCup: [],
                ImperialTablespoon: [],
                ImperialTeaspoon: [],
                CubicInch: [],
                CubicFoot: [],
                CubicMeter: []
            },
            Milliliter: {
                USLiquidGallon: [],
                USLiquidQuart: [],
                USLiquidPint: [],
                USLegalCup: [],
                USTablespoon: [],
                USTeaspoon: [],
                FluidOunce: [],
                Liter: [],
                ImperialFluidOunce: [],
                ImperialGallon: [],
                ImperialQuart: [],
                ImperialPint: [],
                ImperialCup: [],
                ImperialTablespoon: [],
                ImperialTeaspoon: [],
                CubicInch: [],
                CubicFoot: [],
                CubicMeter: []
            },
            Liter: {
                USLiquidGallon: [],
                USLiquidQuart: [],
                USLiquidPint: [],
                USLegalCup: [],
                USTablespoon: [],
                USTeaspoon: [],
                FluidOunce: [],
                Milliliter: [],
                ImperialFluidOunce: [],
                ImperialGallon: [],
                ImperialQuart: [],
                ImperialPint: [],
                ImperialCup: [],
                ImperialTablespoon: [],
                ImperialTeaspoon: [],
                CubicInch: [],
                CubicFoot: [],
                CubicMeter: []
            },
            ImperialFluidOunce: {
                USLiquidGallon: [],
                USLiquidQuart: [],
                USLiquidPint: [],
                USLegalCup: [],
                USTablespoon: [],
                USTeaspoon: [],
                FluidOunce: [],
                Milliliter: [],
                Liter: [],
                ImperialGallon: [],
                ImperialQuart: [],
                ImperialPint: [],
                ImperialCup: [],
                ImperialTablespoon: [],
                ImperialTeaspoon: [],
                CubicInch: [],
                CubicFoot: [],
                CubicMeter: []
            },
            ImperialGallon: {
                USLiquidGallon: [],
                USLiquidQuart: [],
                USLiquidPint: [],
                USLegalCup: [],
                USTablespoon: [],
                USTeaspoon: [],
                FluidOunce: [],
                Milliliter: [],
                Liter: [],
                ImperialFluidOunce: [],
                ImperialQuart: [],
                ImperialPint: [],
                ImperialCup: [],
                ImperialTablespoon: [],
                ImperialTeaspoon: [],
                CubicInch: [],
                CubicFoot: [],
                CubicMeter: []
            },
            ImperialQuart: {
                USLiquidGallon: [],
                USLiquidQuart: [],
                USLiquidPint: [],
                USLegalCup: [],
                USTablespoon: [],
                USTeaspoon: [],
                FluidOunce: [],
                Milliliter: [],
                Liter: [],
                ImperialFluidOunce: [],
                ImperialGallon: [],
                ImperialPint: [],
                ImperialCup: [],
                ImperialTablespoon: [],
                ImperialTeaspoon: [],
                CubicInch: [],
                CubicFoot: [],
                CubicMeter: []
            },
            ImperialPint: {
                USLiquidGallon: [],
                USLiquidQuart: [],
                USLiquidPint: [],
                USLegalCup: [],
                USTablespoon: [],
                USTeaspoon: [],
                FluidOunce: [],
                Milliliter: [],
                Liter: [],
                ImperialFluidOunce: [],
                ImperialGallon: [],
                ImperialQuart: [],
                ImperialCup: [],
                ImperialTablespoon: [],
                ImperialTeaspoon: [],
                CubicInch: [],
                CubicFoot: [],
                CubicMeter: []
            },
            ImperialCup: {
                USLiquidGallon: [],
                USLiquidQuart: [],
                USLiquidPint: [],
                USLegalCup: [],
                USTablespoon: [],
                USTeaspoon: [],
                FluidOunce: [],
                Milliliter: [],
                Liter: [],
                ImperialFluidOunce: [],
                ImperialGallon: [],
                ImperialQuart: [],
                ImperialPint: [],
                ImperialTablespoon: [],
                ImperialTeaspoon: [],
                CubicInch: [],
                CubicFoot: [],
                CubicMeter: []
            },
            ImperialTablespoon: {
                USLiquidGallon: [],
                USLiquidQuart: [],
                USLiquidPint: [],
                USLegalCup: [],
                USTablespoon: [],
                USTeaspoon: [],
                FluidOunce: [],
                Milliliter: [],
                Liter: [],
                ImperialFluidOunce: [],
                ImperialGallon: [],
                ImperialQuart: [],
                ImperialPint: [],
                ImperialCup: [],
                ImperialTeaspoon: [],
                CubicInch: [],
                CubicFoot: [],
                CubicMeter: []
            },
            ImperialTeaspoon: {
                USLiquidGallon: [],
                USLiquidQuart: [],
                USLiquidPint: [],
                USLegalCup: [],
                USTablespoon: [],
                USTeaspoon: [],
                FluidOunce: [],
                Milliliter: [],
                Liter: [],
                ImperialFluidOunce: [],
                ImperialGallon: [],
                ImperialQuart: [],
                ImperialPint: [],
                ImperialCup: [],
                ImperialTablespoon: [],
                CubicInch: [],
                CubicFoot: [],
                CubicMeter: []
            },
            CubicInch: {
                USLiquidGallon: [],
                USLiquidQuart: [],
                USLiquidPint: [],
                USLegalCup: [],
                USTablespoon: [],
                USTeaspoon: [],
                FluidOunce: [],
                Milliliter: [],
                Liter: [],
                ImperialFluidOunce: [],
                ImperialGallon: [],
                ImperialQuart: [],
                ImperialPint: [],
                ImperialCup: [],
                ImperialTablespoon: [],
                ImperialTeaspoon: [],
                CubicFoot: [],
                CubicMeter: []
            },
            CubicFoot: {
                USLiquidGallon: [],
                USLiquidQuart: [],
                USLiquidPint: [],
                USLegalCup: [],
                USTablespoon: [],
                USTeaspoon: [],
                FluidOunce: [],
                Milliliter: [],
                Liter: [],
                ImperialFluidOunce: [],
                ImperialGallon: [],
                ImperialQuart: [],
                ImperialPint: [],
                ImperialCup: [],
                ImperialTablespoon: [],
                ImperialTeaspoon: [],
                CubicInch: [],
                CubicMeter: []
            },
            CubicMeter: {
                USLiquidGallon: [],
                USLiquidQuart: [],
                USLiquidPint: [],
                USLegalCup: [],
                USTablespoon: [],
                USTeaspoon: [],
                FluidOunce: [],
                Milliliter: [],
                Liter: [],
                ImperialFluidOunce: [],
                ImperialGallon: [],
                ImperialQuart: [],
                ImperialPint: [],
                ImperialCup: [],
                ImperialTablespoon: [],
                ImperialTeaspoon: [],
                CubicInch: [],
                CubicFoot: [],
            }
        },
        Time: {
            Millisecond: { // only "exact convert", all others are from google convert'
                Second: ['/', 1000], 
                Minute: ['/', 60000], 
                Hour: ['/', 3600000],
                Day: ['/', 86400000],
                Week: ['/', 604800000],
                Month: ['/', 2628001150],
                Year: ['/', 31536086400] 
            },
            Second: {
                Millisecond: ['x', 1000],
                Minute: ['/', 60],
                Hour: ['/', 3600],
                Day: ['/', 86400],
                Week: ['/', 604800],
                Month: ['/', 2628000],
                Year: ['/', 31540000]
            },
            Minute: {
                Millisecond: ['x', 60000],
                Second: ['x', 60],
                Hour: ['/', 60],
                Day: ['/', 1440],
                Week: ['/', 10080],
                Month: ['/', 43800],
                Year: ['/', 525600]
            },
            Hour: {
                Millisecond: ['x', 3600000],
                Second: ['x', 3600],
                Minute: ['x', 60],
                Day: ['/', 24],
                Week: ['/', 168],
                Month: ['/', 730],
                Year: ['/', 8760]
            },
            Day: {
                Millisecond: ['x', 86400000],
                Second: ['x', 86400],
                Minute: ['x', 1440],
                Hour: ['x', 24],
                Week: ['/', 7],
                Month: ['/', 30.417],
                Year: ['/', 365]
            },
            Week: {
                Millisecond: ['x', 604800000],
                Second: ['x', 604800],
                Minute: ['x', 10080],
                Hour: ['x', 168],
                Day: ['x', 7],
                Month: ['/', 4.345],
                Year: ['/', 52.143]
            },
            Month: {
                Millisecond: ['x', 2628000000],
                Second: ['x', 2628000],
                Minute: ['x', 43800],
                Hour: ['x', 730],
                Day: ['x', 30.417],
                Week: ['x', 4.345],
                Year: ['/', 12]
            },
            Year: {
                Millisecond: ['x', 31540000000],
                Second: ['x', 31540000],
                Minute: ['x', 525600],
                Hour: ['x', 8760],
                Day: ['x', 365],
                Week: ['x', 52.143],
                Month: ['x', 12]
            }
        },
        Temp: {
            Celsius: {

            },
            Kelvin: {

            },
            Fahrenheit: {

            }
        }
    }
}

// const data = {
  
// }

export default data;